CREATE TABLE `intake_submissions` (
	`id` varchar(64) NOT NULL,
	`firstName` varchar(100),
	`lastName` varchar(100),
	`email` varchar(320),
	`phone` varchar(20),
	`businessName` varchar(200),
	`businessStructure` varchar(50),
	`industry` varchar(100),
	`employeeCount` varchar(50),
	`currentRevenue` varchar(50),
	`hasWebsite` varchar(10),
	`hasSocialMedia` varchar(10),
	`selectedServices` text,
	`primaryGoal` text,
	`timeline` varchar(50),
	`budget` varchar(50),
	`priorityRatings` text,
	`preferredContact` varchar(50),
	`bestTimeToCall` varchar(50),
	`additionalInfo` text,
	`status` enum('new','contacted','in_progress','completed') NOT NULL DEFAULT 'new',
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intake_submissions_id` PRIMARY KEY(`id`)
);
